In [1]:
%load_ext autoreload
%autoreload 2
import numpy as np
from unbalanced_cv import get_fold
from sklearn.neighbors import KNeighborsClassifier

In [2]:
# Generate some artificial data
N1 = 10
N2 = 15
N = N1+N2

# Data matrix containing only one feature: the indices of the samples
# Used just for testing the algorithm
data = np.array([np.arange(N)]).T                
classes = np.array([0]*N1 + [1]*N2)

In [14]:
np.arange(N)

25

In [17]:
num_folds = 2
pred_classes = np.full(N, -1)      # Will store the classes predicted by the classifier
for data_train, classes_train, data_test, classes_test, test_indices in get_fold(data, classes, num_folds):
    
    # Train classifier using data_train, classes_train
    knn = KNeighborsClassifier(n_neighbors=3)
    knn.fit(data_train, classes_train)
    
    # Test classifier using data_test, classes_test
    pred = knn.predict(data_test)
    
    # Save predictions
    pred_classes[test_indices] = pred
    
    # Print the indices used in each fold:
    print(f'Objects used for training:\n{data_train}')
    print(f'Classes of the objects used for training:\n{classes_train}')
    print(f'Objects used for testing:\n{data_test}')
    print(f'Classes of the objects used for testing:\n{classes_test}\n')

# All objects should have a predicted class
print(np.sum(pred_classes>=0)==N)

# `pred_classes` can then be compared with `classes` for verifying the accuracy of the classifier
print(np.sum(classes==pred_classes)/N)

Objects used for training:
[[ 6]
 [ 2]
 [ 1]
 [ 4]
 [ 0]
 [10]
 [19]
 [18]
 [17]
 [20]]
Classes of the objects used for training:
[0 0 0 0 0 1 1 1 1 1]
Objects used for testing:
[[ 8]
 [ 5]
 [ 7]
 [ 9]
 [ 3]
 [12]
 [21]
 [15]
 [13]
 [24]
 [14]
 [23]
 [11]
 [22]
 [16]]
Classes of the objects used for testing:
[0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]

Objects used for training:
[[ 8]
 [ 5]
 [ 7]
 [ 9]
 [ 3]
 [12]
 [21]
 [15]
 [13]
 [24]]
Classes of the objects used for training:
[0 0 0 0 0 1 1 1 1 1]
Objects used for testing:
[[ 6]
 [ 2]
 [ 1]
 [ 4]
 [ 0]
 [10]
 [19]
 [18]
 [17]
 [20]]
Classes of the objects used for testing:
[0 0 0 0 0 1 1 1 1 1]

True
0.96


In [1]:
from platform import python_version

print(python_version())

3.6.4
